# Generated by Django 5.0.1 on 2024-01-31 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        ('stations', '0003_remove_station_id_zone_station_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('slot_name', models.CharField(max_length=100)),
                ('slot_status', models.CharField(max_length=100)),
                ('image', models.CharField(default='https://picsum.photos/id/49', max_length=100, null=True)),
                ('bike', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bikes.bike')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.station')),
            ],
        ),
    ]
