# Generated by Django 5.0.1 on 2024-02-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_remove_station_id_zone_station_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_status',
            field=models.CharField(default='Operativa', max_length=100),
        ),
    ]
