# Generated by Django 5.0.1 on 2024-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
