# Generated by Django 5.0.1 on 2024-02-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='open', max_length=20)),
                ('incident_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='slots.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
